version: "3.9"
services:
#  kripticc-feathers:
#    build:
#      context: .
#    container_name: kripticc-feathers-dev
#    ports:
#      - "3030:3030"
#    restart: on-failure
#    depends_on:
#      - postgres
#    links:
#      - postgres
#    volumes:
#      - ./:/kripticc-feathers-dev
#    command: npm start
  postgres:
    image: postgres:14.2-alpine
    container_name: postgres-dev
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5432" ]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kripticc-dev
  redis:
    image: redis:7-alpine
    container_name: redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf
volumes:
  redis-data:
  redis-conf:
  postgres-data:
