version: "3.9"
services:
#  kripticc-feathers:
#    build:
#      context: .
#    container_name: kripticc-feathers-dev
#    ports:
#      - "3030:3030"
#    restart: always
#    depends_on:
#     - postgres
#     - redis
#    volumes:
#      - ./:/kripticc-feathers-dev
#    command: npm start
  postgres:
    image: postgres:latest
    container_name: kripticc-postgres-dev
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kripticc-dev
  redis:
    image: redis:latest
    command: kripticc-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf
volumes:
  redis-data:
  redis-conf:
  postgres-data:
