version: "3.9"
services:
  kripticc-feathers:
    build:
      context: .
    container_name: kripticc-feathers-dev
    ports:
      - "3030:3030"
    restart: always
    depends_on:
     - postgres
     - redis
    volumes:
      - ./:/kripticc-feathers-dev
    command: npm start
